- name: Import base playbook
  import_playbook: base.yml

- hosts: '{{ host }}'
  become: True
  become_user: root
  become_method: su
  roles:
    # Fonts (potential pre-requisite for multiple roles)
    - { role: fonts, tags: fonts }

    # System essential
    - { role: wifi, tags: wifi }
    - { role: bluetooth, tags: bluetooth }
    - { role: pulseaudio, tags: pulseaudio }
    - { role: cups, tags: cups }

    # i3 requires xorg
    - { role: xorg, tags: xorg }
    - { role: i3, tags: i3 }
    - { role: autologin, tags: autologin }

    # kitty (terminal emulator)
    - { role: kitty, tags: kitty }

    # Packages
    - { role: packages, tags: packages }

    # Browsers
    - { role: qutebrowser, tags: qutebrowser,
        when: qutebrowser.install is sameas True }
    - { role: firefox, tags: firefox, when: firefox.install is sameas True }
    - { role: chromium, tags: chromium, when: chromium.install is sameas True }

    # Other non-essential package roles
    - { role: libreoffice, tags: libreoffice }

    # Conditional roles
    - { role: nvidia, tags: nvidia, when: nvidia.install is sameas True }
    - { role: tlp, tags: tlp, when: ansible_form_factor is match('Notebook') }
    - { role: macbook, tags: macbook,
        when: ansible_product_name is search('MacBook') }

