- name: Install Xorg components
  pacman:
    name:
      - xorg-server
      - xorg-xev
      - xorg-xinit
      - xorg-xinput

- name: Set correct X11 keymap
  template:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/

- name: Copy pointer configuration file
  copy:
    src: 30-mouse.conf
    dest: /etc/X11/xorg.conf.d/
  when: xorg.mouse_config is sameas True
