- name: Install virtualisation packages
  pacman:
    name:
      # libvirt and its optional dependencies
      # dmidecode required to supress errors
      - libvirt
      - bridge-utils
      - dmidecode
      - dnsmasq
      - openbsd-netcat
      - qemu-headless
      # To create virtual machines
      - virt-install
      # UEFI firmware
      - ovmf
    state: present

- name: Configure libvirt and QEMU/KVM
  import_tasks: configure.yml

- meta: flush_handlers

- name: Enable and start libvirt services
  systemd:
    name: '{{ item }}'
    enabled: True
    state: started
  with_items:
    - libvirtd.service
    - libvirt-guests.service
