- name: Symlink local fonts
  file:
    src: /usr/local/share/fonts/
    dest: /usr/share/fonts/local
    state: link
    force: True

- name: Copy Windows fonts
  unarchive:
    src: WindowsFonts.tar.gz
    dest: /usr/local/share/fonts/
    mode: 0755
  notify: Refresh fontconfig cache

